### ISSUE TITLE
[app] CLI App for Taker

### ISSUE THREAD

**Issue by rajarshimaitra** [citadel-tech/coinswap#114]
Write a clap app to operate the Taker client. The app code should reside here:

https://github.com/utxo-teleport/teleport-transactions/blob/0898d493f13c93fddd2ff12bfb74b77ef14ea5e4/src/bin/taker.rs#L1-L3

The `taker` app should have the following basic commands:

- `init --data-dir=<optional_datadir> --rpc=<optional_bitcoin_core_rpc>`. This will initialize a taker wallet in the given data directory connected with a bitcoin core rpc. 
- `sync-offers`: syncs its offer book from directory server.
- `list-offers`: list all the known offers.
- `do-coinswap <custom swap params>`: performs a coinswap round with given swap params.

Basic wallet utilities:
- balance: This should return balances in five categories.
  - seed coin
  - swap coin
  - live contract
  - fidelity
  - spendable: seedcoin + swapcoin + live contracts.
  
  - get new address
  - create spend from wallet.

**Comment by PavitraAgarwal21** [comment]
I am interested in taking on this task. Could someone please assign it to me?

**Comment by rajarshimaitra** [comment]
Start with a draft PR, then we will assign it to you.
