### ISSUE TITLE
[app] CLI app for Maker

### ISSUE THREAD

**Issue by rajarshimaitra** [citadel-tech/coinswap#115]
Write a clap app to operate the Maker server. The app code should reside here:

https://github.com/utxo-teleport/teleport-transactions/blob/0898d493f13c93fddd2ff12bfb74b77ef14ea5e4/src/bin/maker.rs#L1-L3

The `maker` app should have the following basic commands:

- `init --data-dir=<optional_datadir> --rpc=<optional_bitcoin_core_rpc>`. This will initialize a taker wallet in the given data directory connected with a bitcoin core rpc. 
- `start server`: start the maker server.

Basic wallet utilities:
- balance: This should return balances in five categories.
  - seed coin
  - swap coin
  - live contract
  - fidelity
  - spendable: seedcoin + swapcoin + live contracts.
  
  - get a new address
  - create spend from the wallet.

**Comment by PavitraAgarwal21** [comment]
I am interested in taking on this task. Could someone please assign it to me?
