### ISSUE TITLE
`SOB/ BDK Wallet`: `Anchor` implementation should contain `WalletStruct` fields

### ISSUE THREAD

**Issue by 15IITian** [citadel-tech/coinswap#168]
In the current situation of `WalletStore` struct -> we use to store all the `multisig & contract redeemscript` of an `incomming/ outgoing`  & `contract` transactions.

Since in BDK -> there is an `Anchor` trait  whose implementation can be used to reference some blockchain data related to a Tx in a block in `Txgraph`. 
https://github.com/bitcoindevkit/bdk/blob/8eef350bd08057acc39b6fc50b1217db5e29b968/crates/chain/src/tx_data_traits.rs#L90 

Since our modified wallet will contain `IndexedTxGraph<A,I>`  which contains  `TxGraph<A>`  -> which is a graph of tx and can traverse through each of them.
Here `Anchor(A)` is generic i.e -> we can store any type of data related to a tx.
 https://github.com/bitcoindevkit/bdk/blob/8eef350bd08057acc39b6fc50b1217db5e29b968/crates/chain/src/indexed_tx_graph.rs#L15
 
 
 IMO, It would be better to put `incoming_swapcoins & outgoing_swapcoins & prevout_to_contract_map` fields to `WalletStruct` into the `Anchor` impl  which will  look like -> 
  
``` rust

   pub struct AnchorImpl{    
    /// The confirmation height of the transaction being anchored.
    pub confirmation_height: u32,
    /// The confirmation time of the transaction being anchored.
    pub confirmation_time: u64,
    /// The anchor block.
    pub anchor_block: BlockId,
    /// tupple of multisig redeemscript with its corresponding incomming swapcoin 
    /// If a tx is funding tx -> it will have Some(..)
    /// Otherwise None
    pub incomming_swapcoin: Option<(ScriptBuf, IncomingSwapCoin)>,
    /// tupple of multisig redeemscript with its corresponding output swapcoin     
    pub outgoing_swapcoins: Option<(ScriptBuf, OutgoingSwapCoin)>,
    /// if a tx is contract tx -> then only it will contain Some(..)
    pub prevout_to_contract_map: Option<(OutPoint, ScriptBuf)>,
    /// if the corresponding tx is related to fedility bond -> then Some(..)
    pub fidelity_bond: Option<(u32, (FidelityBond, ScriptBuf, bool))>,

 }

  ```
 
 
 
 * Since  `TxGraph` has `anchors` field which is used to store all anchors data corresponding to its Tx which are in that `TxGraph`. 
 https://github.com/bitcoindevkit/bdk/blob/8eef350bd08057acc39b6fc50b1217db5e29b968/crates/chain/src/tx_graph.rs#L111
  
* Thus , we can iterate over all anchors data of the txs  -> to get the required information which we now currently store in `WalletStruct`   
  * for eg ->  ` Map of multisig redeemscript to outgoing swapcoins.`

### Benefits of using this approach instead of storing into `WalletStruct`-> 
   * It will help to leverage the `Anchor` trait & `IndexedTxGraph` struct  capabilities -> will help to better utililise the `bdk_chain interface` in more efficient manner.

**Comment by mojoX911** [comment]
ACK. 

Good observation.

Makes sense to me at high-level. Also almost removes the need for a `WalletStore`. I am wondering if we did manage to pull this can we completely remove the wallet store and use the `TXGraph` for everything. 

That will also remove the need to handle a separate wallet store file i/o.

**Comment by 15IITian** [comment]
Three are several downsides which I feel on doing this -> 
  *  not all fields of `WalletStore` can go inside `Anchor` implementation like -> 
`wallet_birthday` , `offer_maxsize` field. 
   
 * But the fields which I talk about above are often used in our code -> thus if we move them to `Anchor` impl  then we have to iterate over `Anchor` instances -> to get the required `HashMap` like `outgoing_swapcoins: HashMap<ScriptBuf, OutgoingSwapCoin>` -> to mitigate this I have 2 approaches-> 
    * Create functions which will iterate to get the required mappings -> but then this will be computational expensive as these functions will be used often.
    * Create independent type alias eg -> `outgoing_swapcoins: HashMap<ScriptBuf, OutgoingSwapCoin>` 
    
    
* If we completely remove `WalletStore` then what will be our backend  , which will implement `PersistentBackend` to have `Persist` staging area.

**Comment by 15IITian** [comment]
>not all fields of WalletStore can go inside Anchor implementation like ->
wallet_birthday 

Though `wallet_birthday` can go inside `wallet` struct.

**Comment by mojoX911** [comment]
Closed as separate WalletStore is better..
