### ISSUE TITLE
Create  one `DERIVATION_PATH` for all keychain kinds

### ISSUE THREAD

**Issue by KnowWhoami** [citadel-tech/coinswap#181]
* Currenlty all we have defined different derivation path for different  types of keychains for eg -> 
   
   https://github.com/citadel-tech/coinswap/blob/a85c9a33cc56619a6c55d35ede2cab0c7f36aa81/src/wallet/api.rs#L40

https://github.com/citadel-tech/coinswap/blob/a85c9a33cc56619a6c55d35ede2cab0c7f36aa81/src/wallet/fidelity.rs#L42

which is redundant .

* thus ,  There is a need to create one uniform `DERIVATION_PATH` which will be used for all  keychain kinds 
  `DERIVATION_PATH= m/84'/0'/0'`

**Comment by wthrajat** [comment]
Done in #192
