### ISSUE TITLE
[improve] Use Amount instead of U64

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#183]
In various places of `contract.rs` we are using `u64` for Bitcoin amounts in sats.
For ex: https://github.com/citadel-tech/coinswap/blob/a85c9a33cc56619a6c55d35ede2cab0c7f36aa81/src/protocol/contract.rs#L55-L66

The latest rust-bitcoin v0.32 streamlined using amounts everywhere as the `Amount` struct. For this reason, we need to make awkward conversions between u64 and Amount in various places in #182 .

Change all the function calls across the library to use `Amount` instead of `u64`.

**Comment by keraliss** [comment]
can i take this?

**Comment by Rohanarora17** [comment]
hey, can I work on this issue?

**Comment by mojoX911** [comment]
@keraliss @Rohanarora17 often better to just do it, instead of asking for permission. Open source is permissionless. Just mention in the issue "I am taking it" and then get at it.
