### ISSUE TITLE
[improve] Use custom fee rate for contract transaction

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#184]
Currently, the Contract transaction fee rates are hardcoded. Which is okay for test cases, but can't work in real production. 

Ex: Contract transaction: https://github.com/citadel-tech/coinswap/blob/a85c9a33cc56619a6c55d35ede2cab0c7f36aa81/src/protocol/contract.rs#L394

Change this function to work with a variable fee rate.

**Comment by Rohanarora17** [comment]
hey, can you elaborate more on whether do you want the fee rate to be one of the parameters in function or want it as a global variable?

**Comment by f3r10** [comment]
could I take this issue?

**Comment by mojoX911** [comment]
Feel free..

**Comment by f3r10** [comment]
Ok, I push a PR. I am not sure if using the fee rate defined on `OngoingSwapState::SwapParams` is correct or would be necessary to define another fee rate only for this case.
