### ISSUE TITLE
Implement Integration Test for Maker's RPC

### ISSUE THREAD

**Issue by Shourya742** [citadel-tech/coinswap#205]
*Task*
* Write a test scenario where a maker is spawned with a backend bitcoind.
* Query the RPC port using an RPC call.

*Details*
* This test should be similar to our existing integration tests.
* Use the test framework to spawn makers.
* Make queries to the maker's RPC port and verify the correctness of the responses.

*Expected Outcome*
* The test should successfully query the maker's RPC port and return correct responses, validating the functionality of the maker's RPC.

**Comment by mojoX911** [comment]
Further info:

This issue is for creating the first template of this type of test. It's okay if all the `maker-cli` commands are not covered in the solving PR. Once the template is ready we can add tests for further commands in subsequent PRs.
