### ISSUE TITLE
Implement Send To Address for maker-cli

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#211]
Add a command in `bin/maker/cli` named `send_to_address` that takes in an `address:amount` string, and sends a transaction to the address with the amount.

The `maker-cli` should pass a new `RPCMsg::SendToAddress` to `makerd`. 

`makerd` should parse the message, get the relevant data, create sign and broadcast the transaction.

`makerd` should log all relevant information of the process.

Add an integration test for this command.

**Comment by BEULAHEVANJALIN** [comment]
Should I pick this up?

**Comment by Shourya742** [comment]
@BEULAHEVANJALIN yup, go ahead.
