### ISSUE TITLE
Implement Do Coinswap command for taker-cli

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#212]
`bin/taker-cli` should have a command named `do-coinswap` which starts the coinswap process. Its as simple as executing the `do_coinswap()` API of Taker.

https://github.com/citadel-tech/coinswap/blob/4818a24c8a7c735f5c3ddc4bb4bee4a1ffa56855/src/taker/api.rs#L245

**Comment by Musab1258** [comment]
@mojoX911 , can I work on this.

**Comment by Shourya742** [comment]
Hey @Musab1258 , sure, go ahead

**Comment by mojoX911** [comment]
Yes @Musab1258 go ahead please. 

Work will be assigned to you at the project board once you make the PR.

**Comment by KnowWhoami** [comment]
Completed via #171 .
