### ISSUE TITLE
Remove unwraps from directory

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#238]
The `src/market/directrory.rs` contains many unwraps. They should return `DiretoryError` instead.

https://github.com/citadel-tech/coinswap/blob/e49fee83d75003d335b16d272eb4e558a7579fbb/src/market/directory.rs#L30-L34

Remove the `Other` error variant and add appropriate variants in its place.

**Comment by jkciw** [comment]
Working on this.
