### ISSUE TITLE
Remove unwraps from Apps

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#239]
The app files are all using `unwraps`. 

We should define a new error in `src/error.rs` named `AppError` which will contain all the other internal errors as variants.

```rust
enum AppError {
    MakerError,
    TakerError,
     DNSError,
}
```

And use `AppError` in the returns of all function calls for app modules.

**Comment by rishkwal** [comment]
Shall I take this?

**Comment by jkciw** [comment]
working on this..

**Comment by RounakJoshi09** [comment]
Hi @jkciw , already started working on this issue , today morning, completed the basic error structure .Planning to complete it by EOD today or most lately by tommorow. If you haven't started on this, or didn't make much difference, please pick other issues. 
Thanks
