### ISSUE TITLE
Improve DNS address book management

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#256]
Currently, the DirectoryServer stores the maker address in an in-memory variable and only writes them to file at shutdown.

This is a bad design. Instead, it should do the following.

- Add an `addresses` mutex in the `DiretoryServer` struct definition.
- Source the `addresses.dat` file if it exists at startup, and populate the `addresses` mutex.
- Use the `DirectoryServer.addresses` to provide RPC responses instead of passing the addresses variable.
- Write the addresses to the file every time it receives a POST request from Maker.

**Comment by aagbotemi** [comment]
@mojoX911 assign this issue to me
