### ISSUE TITLE
Improve Maker Fidelity UX

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#257]
When the maker starts up, it first tries to create the fidelity bonds. If there isn't sufficient balance it will log to the user to send some funds to an address. Once the funds are confirmed then it will create fidelity and carry on with the rest of the operations.

This UX can be enhanced by checking if the funds arrived in the mempool and when it does notify the user that funds are in the mempool and it's waiting for confirmation. 

Once 1 confirmation is received it should notify that to the user and carry on the rest of the operations.

**Comment by aagbotemi** [comment]
@mojoX911 assign this issue to me
