### ISSUE TITLE
`Maker Setup is ready ` is logged out even without fully setup.

### ISSUE THREAD

**Issue by KnowWhoami** [citadel-tech/coinswap#270]
### Description:
https://github.com/citadel-tech/coinswap/blob/dfd55b3ddb282f91c056be81490837930f2b4fff/src/maker/server.rs#L472
- When `start_maker_server` is called during the coinswap process -> after configuring the `fidelity bond` and completing other network-related tasks -> it begins spawning various threads that each perform specific tasks, and then it  calls  `setup_complete`  indicating  that our maker server is ready to use and logs the aforementioned statement.

- However, each thread is responsible for configuring different components of the maker server, which takes time for their full initialization.
- Therefore, it’s not ideal to invoke the `setup_complete` API and log that the server is ready before its entire initialization process is finished.

**Comment by mojoX911** [comment]
Fixed in commit 207d715c9993ce6c1fb182623e9f48b5a43e6c1e
