### ISSUE TITLE
Unintended Creation of Extra Directories when Starting CLI Binaries

### ISSUE THREAD

**Issue by KnowWhoami** [citadel-tech/coinswap#298]
For eg: whenever `directoryd` binary server is started ->  2 other directories  named as `maker` , `taker` having `debug.log` file  are created along with the expected `directory` one  which is not a good UX design.
This similar behaviour happens  if we run `makerd` or `taker` cli app too.

## Expected Outcome: 
Only single directory with the required files must be created whose binary  is being used.

**Comment by mojoX911** [comment]
This is happening because of how the `setup_logger` function is unified for all the apps.

Solution: Use different `setup_logger` functions for different apps. For v0.1.0 this would be the quickest fix.  

This will also be solved once we have our own custom logger.

**Comment by mojoX911** [comment]
Ack on fixing it now with the quick fix. We need individual setup_logger functions for each apps.
