### ISSUE TITLE
Make use of maker fidelity bonds

### ISSUE THREAD

**Issue by mojoX911** [citadel-tech/coinswap#299]
Our current fidelity bond design has various known security bugs. These needs to be fixed with test coverage to ensure the security of the fidelity protocol. 

This issue will mark completion of all immediate and observed bugs in fidelity bonds. Closure of this issue will also include test coverage for the updated designs.

Major updates needed:

- Include fidelity reedem_script in Proof data. Use it to validate that the time lock is correct as claimed.
- Add fidelity verification at DNS. So it can be used to prevent DOS. 
- Add fidelity verification at Taker offerbook. One more layer of validation in case DNS cheats.

**Comment by rishkwal** [comment]
I can take this up

**Comment by Shourya742** [comment]
@rishkwal go ahead...
