### ISSUE TITLE
CLI app runs on `clearnet` even when `-n tor` is passed, with `clearnet` as the default.

### ISSUE THREAD

**Issue by KnowWhoami** [citadel-tech/coinswap#327]
### Description:
When the default network is set to `clearnet`, the server continues running on `clearnet` even if the `-n tor` argument is passed. Setting `tor` as the default network works correctly as done for quick fix in #326 

### Steps to Reproduce:

Set the default network to `clearnet`.
Run the app with `-n tor`.
The server runs on `clearnet` and ignores the `-n tor` argument.

### Expected Behavior:
The app should run on `tor` when `-n tor` is passed.

### Actual Behavior:
If the default is `clearnet`, it still runs on `clearnet`, ignoring the -n tor argument.

### Cause:
The new process created for` tor` does not inherit the parent process's arguments, defaulting to `clearnet`.

**Comment by 007harshmahajan** [comment]
this can be closed as we have defaulted to tor, hence issue in itself solves
