### ISSUE TITLE
Implement configurable mining fees for the maker

### ISSUE THREAD

**Issue by rishkwal** [citadel-tech/coinswap#341]
Currently the mining fees for both funding and contract transactions are set at the taker(#313). This fee should be a part of the Offer sent from the maker to the taker while initiating the swap.

**Comment by KnowWhoami** [comment]
We don't have  to do this because: 
- see https://github.com/citadel-tech/coinswap/issues/313#issuecomment-2561238775.
- We already have an issue for finding suitable `fee_rate` from various sources #199
