### ISSUE TITLE
[test] Integration tests for fidelity operations.

### ISSUE THREAD

**Issue by rajarshimaitra** [citadel-tech/coinswap#97]
# Context
We are doing basic fidelity creation, spending, and validation workflow via our integration test here https://github.com/utxo-teleport/teleport-transactions/blob/master/tests/fidelity.rs

While this covers basic fidelity protocol workflow, some other operations are missing in tests.

Some of the missing wallet ops (there's more): [here](https://github.com/utxo-teleport/teleport-transactions/blob/c30c1089ee0bb457024acf6126c2c7a3fdf997a7/src/wallet/fidelity.rs#L579-L610)

To find further details on fidelity bonds, follow the link in the comment here. (you won't need a lot of fidelity theory to write the tests)  https://github.com/utxo-teleport/teleport-transactions/blob/c30c1089ee0bb457024acf6126c2c7a3fdf997a7/src/wallet/fidelity.rs#L140-L152

# Task:
Extend the existing fidelity integration test to include:
 - `get_expiry()`: Get the expiry in terms of the difficulty adjustment period given an index. This requires RPC access in the wallet.
 - `is_expired()`: Is the fidelity cert at the given index expired?
 - `extend_fidelity_expiry()`: Extend the cert expiry of a given index. 
 - `get_heighest_fidelity_index()`: If multiple bonds are in a wallet, get the one with the highest value. Check `alculate_bond_value()` on how the value for a bond is calculated. This also requires RPC.
 
 # Dev Note: 

 - Write the test to create the semantic meaning of the above operations, instead of matching with what the functions do currently. 

 - Think adversarially about how many ways people can cheat on fidelity or attack a Maker by modifying their fidelity. The test should describe those situations and the functions would need to be refactored if required. So don't follow the functions to write tests, write the tests to assert the function logic or modify functions if needed.

- Use this issue thread to ask further questions.
 
- This is part of our GFI list which is also used for various academic purposes. Comment below that you are taking this up if you decide to work on it.

**Comment by wthrajat** [comment]
Taking this up as a part of our test milestones.

**Comment by wthrajat** [comment]
Clearing the issue assignment if someone wants to work on this issue earlier.
Context: https://github.com/utxo-teleport/teleport-transactions/issues/126#issuecomment-2036615811

**Comment by PavitraAgarwal21** [comment]
Is this task is available for anyone to undertake ?

**Comment by rajarshimaitra** [comment]
Yes. You will get an assignment if you start the work and show us your approach with a draft PR.

**Comment by sivasathyaseeelan** [comment]
> Clearing the issue assignment if someone wants to work on this issue earlier. Context: [#126 (comment)](https://github.com/utxo-teleport/teleport-transactions/issues/126#issuecomment-2036615811)

@rajarshimaitra and @PavitraAgarwal21, I am currently working on this issue. I will submit a PR ASAP!

**Comment by PavitraAgarwal21** [comment]
@rajarshimaitra and @sivasathyaseeelan  I am also started working on that , to submit a draft PR

**Comment by sivasathyaseeelan** [comment]
@PavitraAgarwal21, you can work on this issue. I will catch up some other issue then!

**Comment by mojoX911** [comment]
This issue was completed by #271 . 

Followup Issue for rest of the fidelity fixes is #299 .
